<?php

use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\Auth\AuthController;
use Illuminate\Support\Facades\Route;
use App\HTTP\Controllers\GovernmentController;
use App\Http\Controllers\NewsUpdateController;
use App\HTTP\Controllers\UserController;
use App\HTTP\Controllers\TextWidgetController;
use App\Http\Controllers\UserIndexController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Login;
use App\Models\NewsUpdates;
use Illuminate\Support\Facades\Auth;
use App\Models\Examination;
use App\Models\TextWidget;
use App\Models\Users;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ProfileController;
use Laravolt\Avatar\Avatar;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
// Route::get('/', [Login::class, 'index'])->name('auth/login');


Route::get('/profile', [ProfileController::class, 'show']);

Route::get('/settings', [SettingsController::class, 'index'])->name('settings');
Route::post('/admin/picture/update', [AdminController::class, 'updatePicture'])->name('adminPictureUpdate');


Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');



Route::get('/home', [HomeController::class, 'showProfile']);
Route::get('/', function(){
    $img = Avatar::create('Vince Ramirez')->toBase64();
    return view ('home', ["image" => $img]);
});

Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');
// Login and Registration Routes
Route::get('/', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/', [LoginController::class, 'authenticate'])->name('authenticate');
Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegisterController::class, 'register'])->name('register.post');

// User Dashboard Route (example)
Route::get('/user-index', [UserIndexController::class, 'showData'])->name('user/user-index');

// Other routes...

// Auth routes generated by Laravel's Auth::routes() method
Auth::routes();

// Home route
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



// Route::get('/login', function () {
//     return view('login');
// });
// Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('auth.login');


Route::get('/login', [AuthController::class, 'index'])->name('auth/login');

// Route::get('/signup', function () {
//     return view('signup');
// });
Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');

Route::get('/signup', [AuthController::class, 'signup'])->name('auth/signup');

Route::post('post-signup', [AuthController::class, 'postSignup'])->name('signup.post');



// Route::group([], function(){
//     Route::get('/user-index', [NewsUpdateController::class, 'index'])->name('user/user-index');
//     Route::get('/user-index', [NewsUpdateController::class, 'announce'])->name('user/user-index');
// });

//totoo
// Route::get('/user-index', [UserIndexController::class, 'ShowData'])->name('user/user-index');


// Route::controller(UserIndexController::class)->group(function() {
//     Route::get('/user-index', 'announce')->name('user/user-index');
//     Route::get('/user-index', 'NewsUpdates')->name('user/user-index');
// });



// Route::get('/user-index', [AnnouncementController::class, 'announce'])->name('user/user-index');



///////////////////////////////////////////////////////////////////// simula bago dagadag
Route::get('/user-index-new', function () {
    return view('user/user-index-new');
});

Route::get('/myjobprofile', function () {
    return view('user/myjobprofile');
});

Route::get('/work-experience', function () {
    return view('user/work-experience');
});

Route::get('/education', function () {
    return view('user/education');
});

Route::get('/upload-resume', function () {
    return view('user/upload-resume');
});

Route::get('/skills', function () {
    return view('user/skills');
});

Route::get('/language', function () {
    return view('user/language');
});

Route::get('/additional-info', function () {
    return view('user/additional-info');
});

Route::get('/about', function () {
    return view('user/about');
});

Route::get('/user-resume', [UserIndexController::class, 'DownloadResume'])->name('pdf/user-resume');

/////////////////////////////////////////end DAGDAB



Route::get('/find-jobs', function () {
    return view('find-jobs');
});

Route::get('/government', function () {
    return view('government');
});


Route::get('/job-offers-user',[GovernmentController::class, 'index'])->name('user/job-offers-user');
// Route::get('job-offers-user', function () {
//     return view('user/job-offers-user');
// });
Route::get('/job-clicked-user/{id}', [UserController::class, 'fetch'])->name('user/job-clicked-user');
Route::get('/news-updates-clicked/{id}', [UserIndexController::class,'ShowData'])->name('user/news-updates-clicked');
Route::get('/announcements-clicked/{id}', [UserIndexController::class,'ShowAnnouncements'])->name('user/announcements-clicked');

Route::controller(UserIndexController::class)->group(function() {
    Route::get('/user-index', 'ShowData')->name('user/user-index');
  
    Route::get('/news-updates-clicked/{id}', 'ShowNewsUpdates')->name('user/news-updates-clicked');

    Route::get('/examination-clicked/{id}', 'ShowExam')->name('user/examination-clicked');

 

});

Route::get('government-job-offers', function () {
    return view('user/government-job-offers');
});
Route::get('government-reviews', function () {
    return view('user/government-reviews');
});
Route::get('user-write-review', function () {
    return view('user/user-write-review');
});
Route::get('apply-job', function () {
    return view('user/apply-job');
});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');